#!/bin/bash
npm run build
cp static/CNAME docs
cd docs
git init
git add .
git commit -m "first commit"
git remote add origin https://github.com/pydaylp/pydaylp.github.io.git
git push --force -u origin master
